// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateListInput struct {
	Name string `json:"name"`
}

type JoinListInput struct {
	ListID int `json:"listID"`
}

type SetUserInput struct {
	RealName string `json:"realName"`
	NbaName  string `json:"nbaName"`
}
