// Code generated by entc, DO NOT EDIT.

package db

import (
	"context"
	"fmt"
	"log"

	"github.com/NickDubelman/pickup-list/db/migrate"

	"github.com/NickDubelman/pickup-list/db/list"
	"github.com/NickDubelman/pickup-list/db/nbaplayer"
	"github.com/NickDubelman/pickup-list/db/user"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// List is the client for interacting with the List builders.
	List *ListClient
	// NBAPlayer is the client for interacting with the NBAPlayer builders.
	NBAPlayer *NBAPlayerClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// additional fields for node api
	tables tables
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.List = NewListClient(c.config)
	c.NBAPlayer = NewNBAPlayerClient(c.config)
	c.User = NewUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("db: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("db: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		List:      NewListClient(cfg),
		NBAPlayer: NewNBAPlayerClient(cfg),
		User:      NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:    cfg,
		List:      NewListClient(cfg),
		NBAPlayer: NewNBAPlayerClient(cfg),
		User:      NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		List.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.List.Use(hooks...)
	c.NBAPlayer.Use(hooks...)
	c.User.Use(hooks...)
}

// ListClient is a client for the List schema.
type ListClient struct {
	config
}

// NewListClient returns a client for the List from the given config.
func NewListClient(c config) *ListClient {
	return &ListClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `list.Hooks(f(g(h())))`.
func (c *ListClient) Use(hooks ...Hook) {
	c.hooks.List = append(c.hooks.List, hooks...)
}

// Create returns a create builder for List.
func (c *ListClient) Create() *ListCreate {
	mutation := newListMutation(c.config, OpCreate)
	return &ListCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of List entities.
func (c *ListClient) CreateBulk(builders ...*ListCreate) *ListCreateBulk {
	return &ListCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for List.
func (c *ListClient) Update() *ListUpdate {
	mutation := newListMutation(c.config, OpUpdate)
	return &ListUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ListClient) UpdateOne(l *List) *ListUpdateOne {
	mutation := newListMutation(c.config, OpUpdateOne, withList(l))
	return &ListUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ListClient) UpdateOneID(id int) *ListUpdateOne {
	mutation := newListMutation(c.config, OpUpdateOne, withListID(id))
	return &ListUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for List.
func (c *ListClient) Delete() *ListDelete {
	mutation := newListMutation(c.config, OpDelete)
	return &ListDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *ListClient) DeleteOne(l *List) *ListDeleteOne {
	return c.DeleteOneID(l.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *ListClient) DeleteOneID(id int) *ListDeleteOne {
	builder := c.Delete().Where(list.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ListDeleteOne{builder}
}

// Query returns a query builder for List.
func (c *ListClient) Query() *ListQuery {
	return &ListQuery{
		config: c.config,
	}
}

// Get returns a List entity by its id.
func (c *ListClient) Get(ctx context.Context, id int) (*List, error) {
	return c.Query().Where(list.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ListClient) GetX(ctx context.Context, id int) *List {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a List.
func (c *ListClient) QueryOwner(l *List) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := l.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(list.Table, list.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, list.OwnerTable, list.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(l.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUsers queries the users edge of a List.
func (c *ListClient) QueryUsers(l *List) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := l.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(list.Table, list.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, list.UsersTable, list.UsersPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(l.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ListClient) Hooks() []Hook {
	return c.hooks.List
}

// NBAPlayerClient is a client for the NBAPlayer schema.
type NBAPlayerClient struct {
	config
}

// NewNBAPlayerClient returns a client for the NBAPlayer from the given config.
func NewNBAPlayerClient(c config) *NBAPlayerClient {
	return &NBAPlayerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `nbaplayer.Hooks(f(g(h())))`.
func (c *NBAPlayerClient) Use(hooks ...Hook) {
	c.hooks.NBAPlayer = append(c.hooks.NBAPlayer, hooks...)
}

// Create returns a create builder for NBAPlayer.
func (c *NBAPlayerClient) Create() *NBAPlayerCreate {
	mutation := newNBAPlayerMutation(c.config, OpCreate)
	return &NBAPlayerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of NBAPlayer entities.
func (c *NBAPlayerClient) CreateBulk(builders ...*NBAPlayerCreate) *NBAPlayerCreateBulk {
	return &NBAPlayerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for NBAPlayer.
func (c *NBAPlayerClient) Update() *NBAPlayerUpdate {
	mutation := newNBAPlayerMutation(c.config, OpUpdate)
	return &NBAPlayerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *NBAPlayerClient) UpdateOne(np *NBAPlayer) *NBAPlayerUpdateOne {
	mutation := newNBAPlayerMutation(c.config, OpUpdateOne, withNBAPlayer(np))
	return &NBAPlayerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *NBAPlayerClient) UpdateOneID(id int) *NBAPlayerUpdateOne {
	mutation := newNBAPlayerMutation(c.config, OpUpdateOne, withNBAPlayerID(id))
	return &NBAPlayerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for NBAPlayer.
func (c *NBAPlayerClient) Delete() *NBAPlayerDelete {
	mutation := newNBAPlayerMutation(c.config, OpDelete)
	return &NBAPlayerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *NBAPlayerClient) DeleteOne(np *NBAPlayer) *NBAPlayerDeleteOne {
	return c.DeleteOneID(np.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *NBAPlayerClient) DeleteOneID(id int) *NBAPlayerDeleteOne {
	builder := c.Delete().Where(nbaplayer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &NBAPlayerDeleteOne{builder}
}

// Query returns a query builder for NBAPlayer.
func (c *NBAPlayerClient) Query() *NBAPlayerQuery {
	return &NBAPlayerQuery{
		config: c.config,
	}
}

// Get returns a NBAPlayer entity by its id.
func (c *NBAPlayerClient) Get(ctx context.Context, id int) (*NBAPlayer, error) {
	return c.Query().Where(nbaplayer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *NBAPlayerClient) GetX(ctx context.Context, id int) *NBAPlayer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a NBAPlayer.
func (c *NBAPlayerClient) QueryUser(np *NBAPlayer) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := np.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(nbaplayer.Table, nbaplayer.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, nbaplayer.UserTable, nbaplayer.UserColumn),
		)
		fromV = sqlgraph.Neighbors(np.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *NBAPlayerClient) Hooks() []Hook {
	return c.hooks.NBAPlayer
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Create returns a create builder for User.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryNbaPlayer queries the nba_player edge of a User.
func (c *UserClient) QueryNbaPlayer(u *User) *NBAPlayerQuery {
	query := &NBAPlayerQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(nbaplayer.Table, nbaplayer.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, user.NbaPlayerTable, user.NbaPlayerColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOwnedLists queries the owned_lists edge of a User.
func (c *UserClient) QueryOwnedLists(u *User) *ListQuery {
	query := &ListQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(list.Table, list.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.OwnedListsTable, user.OwnedListsColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryLists queries the lists edge of a User.
func (c *UserClient) QueryLists(u *User) *ListQuery {
	query := &ListQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(list.Table, list.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, user.ListsTable, user.ListsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}
