// Code generated by entc, DO NOT EDIT.

package db

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NickDubelman/pickup-list/db/nbaplayer"
	"github.com/NickDubelman/pickup-list/db/predicate"
)

// NBAPlayerDelete is the builder for deleting a NBAPlayer entity.
type NBAPlayerDelete struct {
	config
	hooks    []Hook
	mutation *NBAPlayerMutation
}

// Where appends a list predicates to the NBAPlayerDelete builder.
func (npd *NBAPlayerDelete) Where(ps ...predicate.NBAPlayer) *NBAPlayerDelete {
	npd.mutation.Where(ps...)
	return npd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (npd *NBAPlayerDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(npd.hooks) == 0 {
		affected, err = npd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NBAPlayerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			npd.mutation = mutation
			affected, err = npd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(npd.hooks) - 1; i >= 0; i-- {
			if npd.hooks[i] == nil {
				return 0, fmt.Errorf("db: uninitialized hook (forgotten import db/runtime?)")
			}
			mut = npd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, npd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (npd *NBAPlayerDelete) ExecX(ctx context.Context) int {
	n, err := npd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (npd *NBAPlayerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: nbaplayer.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nbaplayer.FieldID,
			},
		},
	}
	if ps := npd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, npd.driver, _spec)
}

// NBAPlayerDeleteOne is the builder for deleting a single NBAPlayer entity.
type NBAPlayerDeleteOne struct {
	npd *NBAPlayerDelete
}

// Exec executes the deletion query.
func (npdo *NBAPlayerDeleteOne) Exec(ctx context.Context) error {
	n, err := npdo.npd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nbaplayer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (npdo *NBAPlayerDeleteOne) ExecX(ctx context.Context) {
	npdo.npd.ExecX(ctx)
}
