// Code generated by entc, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NickDubelman/pickup-list/db/nbaplayer"
)

// NBAPlayer is the model entity for the NBAPlayer schema.
type NBAPlayer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NBAPlayer) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case nbaplayer.FieldID:
			values[i] = new(sql.NullInt64)
		case nbaplayer.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type NBAPlayer", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NBAPlayer fields.
func (np *NBAPlayer) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case nbaplayer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			np.ID = int(value.Int64)
		case nbaplayer.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				np.Name = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this NBAPlayer.
// Note that you need to call NBAPlayer.Unwrap() before calling this method if this NBAPlayer
// was returned from a transaction, and the transaction was committed or rolled back.
func (np *NBAPlayer) Update() *NBAPlayerUpdateOne {
	return (&NBAPlayerClient{config: np.config}).UpdateOne(np)
}

// Unwrap unwraps the NBAPlayer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (np *NBAPlayer) Unwrap() *NBAPlayer {
	tx, ok := np.config.driver.(*txDriver)
	if !ok {
		panic("db: NBAPlayer is not a transactional entity")
	}
	np.config.driver = tx.drv
	return np
}

// String implements the fmt.Stringer.
func (np *NBAPlayer) String() string {
	var builder strings.Builder
	builder.WriteString("NBAPlayer(")
	builder.WriteString(fmt.Sprintf("id=%v", np.ID))
	builder.WriteString(", name=")
	builder.WriteString(np.Name)
	builder.WriteByte(')')
	return builder.String()
}

// NBAPlayers is a parsable slice of NBAPlayer.
type NBAPlayers []*NBAPlayer

func (np NBAPlayers) config(cfg config) {
	for _i := range np {
		np[_i].config = cfg
	}
}
