// Code generated by entc, DO NOT EDIT.

package db

import (
	"time"

	"github.com/NickDubelman/pickup-list/db/list"
	"github.com/NickDubelman/pickup-list/db/schema"
	"github.com/NickDubelman/pickup-list/db/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	listFields := schema.List{}.Fields()
	_ = listFields
	// listDescCreatedAt is the schema descriptor for created_at field.
	listDescCreatedAt := listFields[1].Descriptor()
	// list.DefaultCreatedAt holds the default value on creation for the created_at field.
	list.DefaultCreatedAt = listDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[2].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
