// Code generated by entc, DO NOT EDIT.

package nbaplayer

const (
	// Label holds the string label denoting the nbaplayer type in the database.
	Label = "nba_player"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the nbaplayer in the database.
	Table = "nba_players"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "nba_players"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_nba_player"
)

// Columns holds all SQL columns for nbaplayer fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "nba_players"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_nba_player",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
