// Code generated by entc, DO NOT EDIT.

package nbaplayer

const (
	// Label holds the string label denoting the nbaplayer type in the database.
	Label = "nba_player"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the nbaplayer in the database.
	Table = "nba_players"
)

// Columns holds all SQL columns for nbaplayer fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
